server:
  port: 11112
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yueyou
    username: root
    password: X1y1y1@d1m1w1
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mvc:
    path match:
      matching-strategy: ant_path_matcher