server:
  port: 11112
spring:
  profiles:
    active: dev
  servlet:
    context-path: /api
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/yueyou
    username: root
    password: X1y1y1@d1m1w1
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  session:
    timeout: 86400
    # 使用logback.xml来配置日志
    logging:
      config=classpath: logback.xml


